- name: Framework Screen
  id:
    model: NE135A1M-NY1
    serial:
  position: center
- name: Old Framework Screen
  id:
    model: "0x095F"
    serial:
  position: center
- name: Office LG
  id:
    model: LG HDR 4K
    serial: 207NTZN77253
  position: above
- name: Office Dell
  id:
    model: DELL P2722H
    serial: 114V1M3
  position: unknown
- name: Home GN950
  id:
    model: 27GN950
    serial: 111NTHMH2169
  position: right
- name: Nicole LG
  id:
    model: LG HDR 4K
    serial: "0x00049EDF"
  position: above
- name: Salesforce Widescreens
  id:
    model: DELL U3425WE
  position: above
  #serial: 59JP3Z3
